services:
  - type: web
    name: lector-codigo-barras-icg
    runtime: python
    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: lector_barcode
      - key: COLLECTION_NAME
        value: registros
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
